[workspace]
members = [
  "hub",
  "seat"
]

[workspace.dependencies]
ownable = { path = "modules/ownable" }
metadata = { path = "modules/metadata" }
token = { path = "modules/token" }
sellable = { path = "modules/sellable" }